
name: Test it
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup tarantool
        uses: ./
        with:
          tarantool-version: "2.7.0"
